name: Java CI

on:
  create:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Clean
        run: ./gradlew ui:clean
      - name: Assemble
        run: ./gradlew ui:assemble
      - name: Install
        run: ./gradlew ui:install
      - name: Upload
        run: ./gradlew ui:bintrayUpload
        env:
          bintrayUsername: ${{ secrets.bintrayUsername }}
          bintrayApiKey: ${{ secrets.bintrayApiKey }}
