name: Continuous Deployment

on:
  push:
    tags:
      - v*

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Clean
        run: ./gradlew ui:clean
      - name: Assemble
        run: ./gradlew ui:assemble
      - name: Install
        run: ./gradlew ui:install
      # Base64 decodes and pipes the GPG key content into the secret file
      - name: Prepare environment
        env:
          GPG_KEY: ${{ secrets.ANDROID_GPG_KEY }}
          SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.ANDROID_SECRET_RING_FILE }}
        run: |
          git fetch --unshallow
          sudo bash -c "echo '$GPG_KEY' | base64 -d > '$SIGNING_SECRET_KEY_RING_FILE'"
      - name: Publish to Maven Central
        run: ./gradlew :build-gradle-plugin:publishReleasePublicationToSonatypeRepository --max-workers 1 :build-gradle-plugin:closeAndReleaseRepository
        env:
          OSSRH_USERNAME: ${{ secrets.ANDROID_OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.ANDROID_OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.ANDROID_SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.ANDROID_SIGNING_PASSWORD }}
          SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.ANDROID_SECRET_RING_FILE }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.ANDROID_SONATYPE_STAGING_ID }}